name: readme-quote

on:
  push:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  add_quote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update quote in readme
      run: |-
        QUOTE=$(curl -s "https://zenquotes.io/api/random" |jq -r ".[].h")
        echo "${QUOTE:=>Silence is Golden}"
        sed -i "/^<blockquote>/d" README.md
        sed -i "/^<\!-- #quote-start -->/a\ $QUOTE" README.md
        git diff
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git add README.md
        git diff --quiet || (git add README.md && git commit -m "Added new quote to README")
        git push origin main